# Generated by Django 5.2.3 on 2025-06-24 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeysMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(max_length=20)),
                ('public_key', models.TextField()),
                ('private_key', models.TextField()),
                ('user_shared', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='DecryptionFiles',
            fields=[
                ('d_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=20)),
                ('file_extension', models.CharField(max_length=5)),
                ('file', models.FileField(upload_to='decrypted_uploads/')),
                ('filesize', models.FloatField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('filesize', models.FloatField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shared', models.BooleanField(default=False)),
                ('share_token', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('key_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('key_name', models.CharField(max_length=100)),
                ('key_type', models.TextField()),
                ('key_size', models.IntegerField(default=2048)),
                ('public_key', models.TextField()),
                ('private_key', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EncryptionFiles',
            fields=[
                ('e_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=20)),
                ('file_extension', models.CharField(max_length=5)),
                ('file', models.FileField(upload_to='encrypted_uploads/')),
                ('filesize', models.FloatField()),
                ('shared_with', models.JSONField(default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('private_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.keys')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='default.jpg', upload_to='profile_pics/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
