# Generated by Django 5.2.3 on 2025-06-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decryptionfiles',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='encryptionfiles',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
    ]
