# Generated by Django 5.2.3 on 2025-06-25 12:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_publicfileshare_delete_keysmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicfileshare',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
